from __future__ import absolute_import, division, print_function

import os


ICON_RELATIVE_DIRECTORY = os.path.join("branding", "icons", "runtime", "aminate-toolbar")


WORKFLOW_ICON_MANIFEST = (
    {
        "id": "quick_start",
        "display_name": "Quick Start",
        "command": "workflow_quick_start",
        "tab": "quick_start",
        "label": "QS",
        "asset": "icon_quick_start.svg",
        "accent": "#56D7E8",
        "purpose": "Open Aminate's fastest start path.",
        "help": "Pick a tool, read its short guide, then begin.",
        "shortcut": None,
    },
    {
        "id": "toolkit_bar",
        "display_name": "Toolkit Bar",
        "command": "workflow_toolkit_bar",
        "tab": "toolkit_bar",
        "label": "TB",
        "asset": "icon_toolkit_bar.svg",
        "accent": "#6FA8FF",
        "purpose": "Open compact animation controls.",
        "help": "Use key plus timing commands without changing tabs.",
        "shortcut": None,
    },
    {
        "id": "scene_helpers",
        "display_name": "Scene Helpers",
        "command": "workflow_scene_helpers",
        "tab": "scene_helpers",
        "label": "SH",
        "asset": "icon_scene_helpers.svg",
        "accent": "#5D98E8",
        "purpose": "Apply scene setup plus cleanup helpers.",
        "help": "Use Auto Key, snapping, render setup, recovery, plus cleanup.",
        "shortcut": None,
    },
    {
        "id": "reference_manager",
        "display_name": "Reference Manager",
        "command": "workflow_reference_manager",
        "tab": "reference_manager",
        "label": "RM",
        "asset": "icon_reference_manager.svg",
        "accent": "#43D4C0",
        "purpose": "Collect scene files plus linked assets.",
        "help": "Save the scene, then build a portable transfer package.",
        "shortcut": None,
    },
    {
        "id": "dynamic_parenting",
        "display_name": "Dynamic Parenting",
        "command": "workflow_dynamic_parenting",
        "tab": "dynamic_parenting",
        "label": "DP",
        "asset": "icon_dynamic_parenting.svg",
        "accent": "#A6D96A",
        "purpose": "Create temporary parent relationships.",
        "help": "Move a selected control without rebuilding the rig.",
        "shortcut": None,
    },
    {
        "id": "hand_foot_hold",
        "display_name": "Hand / Foot Hold",
        "command": "workflow_hand_foot_hold",
        "tab": "hand_foot_hold",
        "label": "HF",
        "asset": "icon_hand_foot_hold.svg",
        "accent": "#D3E85C",
        "purpose": "Hold a hand or foot in place.",
        "help": "Set, edit, or clear a contact hold.",
        "shortcut": None,
    },
    {
        "id": "surface_contact",
        "display_name": "Surface Contact",
        "command": "workflow_surface_contact",
        "tab": "surface_contact",
        "label": "SC",
        "asset": "icon_surface_contact.svg",
        "accent": "#FFC857",
        "purpose": "Keep feet or props on a surface.",
        "help": "Find contact plus reduce unwanted sliding.",
        "shortcut": None,
    },
    {
        "id": "dynamic_pivot",
        "display_name": "Dynamic Pivot",
        "command": "workflow_dynamic_pivot",
        "tab": "dynamic_pivot",
        "label": "PV",
        "asset": "icon_dynamic_pivot.svg",
        "accent": "#FF9D5C",
        "purpose": "Move the working pivot for the current action.",
        "help": "Restore the original pivot when finished.",
        "shortcut": None,
    },
    {
        "id": "universal_ik_fk",
        "display_name": "Universal IK/FK",
        "command": "workflow_ikfk",
        "tab": "ikfk",
        "label": "IK",
        "asset": "icon_universal_ik_fk.svg",
        "accent": "#FF7D77",
        "purpose": "Switch between IK plus FK control.",
        "help": "Match the current pose before switching.",
        "shortcut": None,
    },
    {
        "id": "controls_retargeter",
        "display_name": "Controls Retargeter",
        "command": "workflow_retarget",
        "tab": "controls_retargeter",
        "label": "RT",
        "asset": "icon_controls_retargeter.svg",
        "accent": "#E989A9",
        "purpose": "Transfer animation between controls or rigs.",
        "help": "Map source controls to target controls before baking.",
        "shortcut": None,
    },
    {
        "id": "control_picker",
        "display_name": "Control Picker",
        "command": "workflow_picker",
        "tab": "control_picker",
        "label": "CP",
        "asset": "icon_control_picker.svg",
        "accent": "#C0A2FF",
        "purpose": "Select rig controls from the viewport.",
        "help": "Click a picker control to select the matching rig part.",
        "shortcut": None,
    },
    {
        "id": "animators_pencil",
        "display_name": "Animator's Pencil",
        "command": "workflow_pencil",
        "tab": "animators_pencil",
        "label": "PN",
        "asset": "icon_animators_pencil.svg",
        "accent": "#FFC238",
        "purpose": "Draw animation notes plus pose guides.",
        "help": "Pick a brush, colour, plus layer, then draw in the viewport.",
        "shortcut": "E",
        "shortcut_help": "Switch to Eraser while the Pencil panel is active.",
    },
    {
        "id": "animation_assistant",
        "display_name": "Animation Assistant",
        "command": "workflow_animation_assistant",
        "tab": "animation_assistant",
        "label": "AA",
        "asset": "icon_animation_assistant.svg",
        "accent": "#B77BFF",
        "purpose": "Run guided animation helpers.",
        "help": "Use focused assistance for common pose tasks.",
        "shortcut": None,
    },
    {
        "id": "animation_styling",
        "display_name": "Animation Styling",
        "command": "workflow_animation_styling",
        "tab": "animation_styling",
        "label": "AS",
        "asset": "icon_animation_styling.svg",
        "accent": "#F5B070",
        "purpose": "Shape timing, spacing, plus motion feel.",
        "help": "Edit curves, keys, plus animation spacing.",
        "shortcut": None,
    },
    {
        "id": "history_timeline",
        "display_name": "History Timeline",
        "command": "workflow_history",
        "tab": "history_timeline",
        "label": "HT",
        "asset": "icon_history_timeline.svg",
        "accent": "#F58B87",
        "purpose": "Review saved scene states plus timeline history.",
        "help": "Return to an earlier Aminate snapshot when supported.",
        "shortcut": None,
    },
    {
        "id": "onion_skin",
        "display_name": "Onion Skin",
        "command": "workflow_onion",
        "tab": "onion_skin",
        "label": "OS",
        "asset": "icon_onion_skin.svg",
        "accent": "#B89AB0",
        "purpose": "See nearby poses while editing this frame.",
        "help": "Adjust frame range, opacity, plus colour.",
        "shortcut": None,
    },
    {
        "id": "rotation_doctor",
        "display_name": "Rotation Doctor",
        "command": "workflow_rotation",
        "tab": "rotation_doctor",
        "label": "RD",
        "asset": "icon_rotation_doctor.svg",
        "accent": "#97D58A",
        "purpose": "Find plus repair rotation problems.",
        "help": "Check animated rotations for flips, drift, or gimbal risk.",
        "shortcut": None,
    },
    {
        "id": "character_skinning",
        "display_name": "Character Skinning",
        "command": "workflow_skin",
        "tab": "skinning_cleanup",
        "label": "SK",
        "asset": "icon_character_skinning.svg",
        "accent": "#23C7B7",
        "purpose": "Inspect mesh deformation plus joint influence.",
        "help": "Find weighting, scale, or deformation trouble.",
        "shortcut": None,
    },
    {
        "id": "rig_scale",
        "display_name": "Rig Scale",
        "command": "workflow_rig_scale",
        "tab": "rig_scale",
        "label": "RS",
        "asset": "icon_rig_scale.svg",
        "accent": "#B4D86A",
        "purpose": "Scale a rig for export-safe handoff.",
        "help": "Set the target size, create the copy, then verify animation.",
        "shortcut": None,
    },
    {
        "id": "video_reference",
        "display_name": "Video Reference",
        "command": "workflow_video",
        "tab": "video_reference",
        "label": "VR",
        "asset": "icon_video_reference.svg",
        "accent": "#6CC5FF",
        "purpose": "Place image or video reference in the scene.",
        "help": "Load, scrub, plus keep reference timing visible.",
        "shortcut": None,
    },
    {
        "id": "timeline_notes",
        "display_name": "Timeline Notes",
        "command": "workflow_timeline",
        "tab": "timeline_notes",
        "label": "TN",
        "asset": "icon_timeline_notes.svg",
        "accent": "#8EA4FF",
        "purpose": "Attach notes to exact frame ranges.",
        "help": "Use notes for feedback, shots, plus reminders.",
        "shortcut": None,
    },
    {
        "id": "smear_frames",
        "display_name": "Smear Frames",
        "command": "workflow_smear_frames",
        "tab": "smear_frames",
        "label": "SF",
        "asset": "icon_smear_frames.svg",
        "accent": "#D48BCF",
        "purpose": "Build readable motion between key poses.",
        "help": "Create or preview smear frames for fast action.",
        "shortcut": None,
    },
    {
        "id": "customization",
        "display_name": "Customization",
        "command": "workflow_customization",
        "tab": "customization",
        "label": "CU",
        "asset": "icon_customization.svg",
        "accent": "#83B5C9",
        "purpose": "Change Aminate tools plus preferences.",
        "help": "Choose visible tools, hover help, shortcuts, plus settings.",
        "shortcut": None,
    },
)


ACTION_ICON_MANIFEST = (
    {
        "id": "action_nudge_left",
        "display_name": "Nudge Left",
        "accessible_label": "Move selected animation one frame earlier",
        "command": "nudge_left",
        "label": "-1",
        "asset": "icon_action_nudge_left.svg",
        "accent": "#EF6F6C",
        "purpose": "Move selected animation one frame earlier.",
        "help": "Selected Graph Editor keys take priority; otherwise all keys on selected controls move together.",
        "shortcut": None,
    },
    {
        "id": "action_nudge_right",
        "display_name": "Nudge Right",
        "accessible_label": "Move selected animation one frame later",
        "command": "nudge_right",
        "label": "+1",
        "asset": "icon_action_nudge_right.svg",
        "accent": "#55CBCD",
        "purpose": "Move selected animation one frame later.",
        "help": "Selected Graph Editor keys take priority; otherwise all keys on selected controls move together.",
        "shortcut": None,
    },
    {
        "id": "action_insert_inbetween",
        "display_name": "Insert Inbetween",
        "accessible_label": "Insert an inbetween key on the current frame",
        "command": "insert_inbetween",
        "label": "In",
        "asset": "icon_action_insert_inbetween.svg",
        "accent": "#F6C85F",
        "purpose": "Insert an inbetween key at the current frame.",
        "help": "Keys selected animated controls without removing the surrounding timing poses.",
        "shortcut": None,
    },
    {
        "id": "action_tween_machine",
        "display_name": "Tween Machine",
        "accessible_label": "Open Tween Machine for the current frame",
        "command": "tween_machine",
        "label": "Tween",
        "asset": "icon_action_tween_machine.svg",
        "accent": "#4CC9F0",
        "purpose": "Blend the current pose between nearby keys.",
        "help": "Drag a percentage between the previous and next keyed poses, then commit the result.",
        "shortcut": None,
    },
    {
        "id": "action_cut_key",
        "display_name": "Cut Current Key",
        "accessible_label": "Remove selected controls keys from the current frame",
        "command": "remove_current",
        "label": "Cut",
        "asset": "icon_action_cut_key.svg",
        "accent": "#B86BFF",
        "purpose": "Remove keys from the current frame.",
        "help": "Only current-frame keys on selected animated controls are removed; other frames stay unchanged.",
        "shortcut": None,
    },
    {
        "id": "action_reset_pose",
        "display_name": "Reset Pose",
        "accessible_label": "Reset selected controls transform values",
        "command": "reset_pose",
        "label": "Zero",
        "asset": "icon_action_reset_pose.svg",
        "accent": "#7BD88F",
        "purpose": "Reset selected controls to neutral transforms.",
        "help": "Translation and rotation return to zero; scale returns to one on settable channels.",
        "shortcut": None,
    },
    {
        "id": "action_bake_twos",
        "display_name": "Bake On Twos",
        "accessible_label": "Bake selected animation every two frames",
        "command": "bake_twos",
        "label": "2s",
        "asset": "icon_action_bake_twos.svg",
        "accent": "#72B7F2",
        "purpose": "Bake selected controls every two frames.",
        "help": "Writes stepped pose samples across the playback range, increasing the number of keys.",
        "shortcut": None,
    },
    {
        "id": "action_select_animated",
        "display_name": "Select Animated",
        "accessible_label": "Select every animated transform in the scene",
        "command": "select_animated",
        "label": "Anim",
        "asset": "icon_action_select_animated.svg",
        "accent": "#95E6E8",
        "purpose": "Select every animated transform in the scene.",
        "help": "Finds transforms connected to animation curves so the full animated set can be edited together.",
        "shortcut": None,
    },
    {
        "id": "action_clean_static",
        "display_name": "Clean Static Keys",
        "accessible_label": "Remove animation curves whose values never change",
        "command": "clean_static",
        "label": "Clean",
        "asset": "icon_action_clean_static.svg",
        "accent": "#B9E769",
        "purpose": "Remove animation curves that never change value.",
        "help": "Only constant curves on selected controls are deleted; review the result with Maya Undo available.",
        "shortcut": None,
    },
    {
        "id": "action_combine_freeze_pivot",
        "display_name": "Combine Freeze Pivot",
        "accessible_label": "Combine selected meshes freeze transforms and edit pivot",
        "command": "combine_freeze_pivot",
        "label": "CFP",
        "asset": "icon_action_combine_freeze_pivot.svg",
        "accent": "#55CBCD",
        "purpose": "Combine meshes, freeze transforms, then edit the pivot.",
        "help": "This changes selected mesh structure; use Maya Undo if the combined result is not wanted.",
        "shortcut": None,
    },
    {
        "id": "action_package_scene_zip",
        "display_name": "Package Scene",
        "accessible_label": "Package the scene and linked files into a zip archive",
        "command": "package_scene_zip",
        "label": "Zip",
        "asset": "icon_action_package_scene_zip.svg",
        "accent": "#F4A261",
        "purpose": "Package the scene plus linked files into one zip.",
        "help": "Saves first, gathers references, textures, image planes, audio, and caches, then opens the package folder.",
        "shortcut": None,
    },
    {
        "id": "action_playblast_1080p",
        "display_name": "Playblast 1080p AVI",
        "accessible_label": "Playblast the playback range to Documents at 1080p",
        "command": "playblast_1080p",
        "label": "PB",
        "asset": "icon_action_playblast_1080p.svg",
        "accent": "#FF7A59",
        "purpose": "Playblast the playback range at 1080p full scale.",
        "help": "Creates a 1920 by 1080 AVI in the current Windows user's Documents folder.",
        "shortcut": None,
    },
    {
        "id": "action_export_selected_animation_fbx",
        "display_name": "Export Selected Animation FBX",
        "accessible_label": "Export selected animation to FBX",
        "command": "export_selected_animation_fbx",
        "label": "FBX",
        "asset": "icon_action_export_selected_animation_fbx.svg",
        "accent": "#66D9EF",
        "purpose": "Export selected objects as FBX using the visible playback range.",
        "help": "Bakes geometry, skinning, blend shapes, tangents/binormals, materials/textures, and embedded media; cameras and lights stay off by default.",
        "shortcut": None,
    },
    {
        "id": "game_animation_mode",
        "display_name": "Game Animation Mode",
        "accessible_label": "Apply enabled game animation scene settings",
        "command": "game_animation_mode",
        "label": "Game",
        "asset": "icon_game_animation_mode.svg",
        "active_asset": "icon_game_animation_mode_active.svg",
        "accent": "#4EBFFF",
        "purpose": "Apply the enabled game-animation scene settings.",
        "help": "Uses the checked options for 30 fps, realtime playback, autosave, textures, tangents, and viewport updates.",
        "shortcut": None,
    },
)


WORKFLOW_ICON_BY_COMMAND = dict((entry["command"], entry) for entry in WORKFLOW_ICON_MANIFEST)
WORKFLOW_ICON_BY_TAB = dict((entry["tab"], entry) for entry in WORKFLOW_ICON_MANIFEST)
ACTION_ICON_BY_COMMAND = dict((entry["command"], entry) for entry in ACTION_ICON_MANIFEST)


def workflow_toolbar_tools():
    return tuple(
        {
            "command": entry["command"],
            "tab": entry["tab"],
            "label": entry["label"],
            "color": entry["accent"],
            "glyph": entry["id"],
            "tooltip": "{0}: {1} {2}".format(entry["display_name"], entry["purpose"], entry["help"]),
            "purpose": entry["purpose"],
            "help": entry["help"],
            "shortcut": entry.get("shortcut"),
            "shortcut_help": entry.get("shortcut_help"),
            "asset": entry["asset"],
        }
        for entry in WORKFLOW_ICON_MANIFEST
    )


def action_toolbar_tools():
    return tuple(dict(entry) for entry in ACTION_ICON_MANIFEST)


def icon_entry(command=None, tab=None):
    if command:
        command_name = str(command)
        return WORKFLOW_ICON_BY_COMMAND.get(command_name) or ACTION_ICON_BY_COMMAND.get(command_name)
    if tab:
        return WORKFLOW_ICON_BY_TAB.get(str(tab))
    return None


def icon_path(command=None, tab=None, module_root=None, active=False):
    entry = icon_entry(command=command, tab=tab)
    if not entry:
        return ""
    root = module_root or os.path.dirname(os.path.abspath(__file__))
    asset = entry.get("active_asset") if active else None
    return os.path.join(root, ICON_RELATIVE_DIRECTORY, asset or entry["asset"])
